### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by George7h** [sheezu900/My_Potfolio#8]
Create button styling for Portfolio, About and Contact

**Comment by shahzaman900** [comment]
> Create button styling for Portfolio, About, and Contact

I will try to fix it.
Thank you George

**Comment by AbuTalha3** [comment]
Please consult figma design and use the colors mentioned in figma deign to make an exact copy of web page.

**Comment by AbuTalha3** [comment]
You have overall made a good Web Design. Keep up the good work. Happy Coding
