### ISSUE TITLE
URL issues

### ISSUE THREAD

**Issue by jecode93** [sheezu900/My_Potfolio#9]
https://github.com/sheezu900/My_Potfolio/blob/50b1495b60d9d1fd1b73d8962f9fc415f0e76367/style.css#L158

I could suggest you change this URL path : 
it should be url("./images/header-shapes/mobile.svg")

**Comment by shahzaman900** [comment]
### Thank you @jecode93  for the suggestion.

I will try to fix it.
Thank you.
